# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouton',
            name='in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='birth_siblings',
            field=models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='race',
            field=models.CharField(blank=True, choices=[('BLEU DU MAINE', 'BLEU DU MAINE'), ('TEXEL', 'TEXEL'), ('BLEU TEXEL', 'BLEU TEXEL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='sex',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1),
        ),
    ]
