# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0002_auto_20170613_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouton',
            name='birth_date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
