# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0003_mouton_birth_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouton',
            name='birth_siblings',
            field=models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Triple', 'Triple'), ('Quadruple', 'Quadruple')], max_length=50),
        ),
    ]
