# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0004_auto_20170613_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouton',
            name='sold_value',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
