# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0005_auto_20170613_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='Treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
