# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0006_auto_20170613_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouton',
            name='fourth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='one_month_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='third_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='two_month_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
