# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0007_auto_20170613_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='Treatment',
            new_name='treatment',
        ),
    ]
