# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0011_auto_20170617_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouton',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
