# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0012_auto_20170617_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='mouton',
            name='out_text',
            field=models.CharField(blank=True, choices=[('V', 'V'), ('A', 'A'), ('M', 'M')], max_length=5),
        ),
    ]
