# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0013_auto_20170703_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouton',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
