# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 20:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0017_auto_20171108_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouton',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='birth_date2',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance 2'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='birth_siblings',
            field=models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Triple', 'Triple'), ('Quadruple', 'Quadruple')], max_length=50, verbose_name='naissance multiple'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='birth_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, verbose_name='poid à la naissance'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='comment',
            field=models.TextField(blank=True, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='father',
            field=models.CharField(blank=True, max_length=50, verbose_name='père'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='in_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'entrée"),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='in_text',
            field=models.CharField(blank=True, max_length=5, verbose_name="commentaire d'entrée"),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='mother',
            field=models.CharField(blank=True, max_length=50, verbose_name='mère'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='out_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de sortie'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='out_text',
            field=models.CharField(blank=True, choices=[('V', 'V'), ('A', 'A'), ('M', 'M')], max_length=5, verbose_name='commentaire de sortie'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='sanitel_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4,5}(\\-\\-)?\\d{4}$', 'Sanitel doit avoir 8 ou 9 chiffres')], verbose_name='n° Sanitel'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='sex',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1, verbose_name='sexe'),
        ),
    ]
