# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0018_auto_20171108_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='mouton',
            name='birth_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='poid à la naissance'),
        ),
    ]
