# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0019_auto_20171122_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouton',
            name='lot_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moutons.Lot'),
        ),
    ]
