# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0020_auto_20171226_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouton',
            old_name='birth',
            new_name='birth_comment',
        ),
    ]
