# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0021_auto_20171227_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutte',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lutte',
            name='date_lutte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='male_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='moutons.Mouton'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='mouton_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='moutons.Mouton'),
        )
    ]
