# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0022_auto_20180120_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutte',
            name='bred_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
