# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0023_auto_20180120_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutte',
            name='alive_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='dead_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
