# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0025_auto_20180121_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutte',
            name='alive_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de vivant'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='birth_weight_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='poid naissance 1'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='birth_weight_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='poid naissance 2'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='birth_weight_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='poid naissance 3'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='bred_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre élevé'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='date_lutte',
            field=models.DateField(blank=True, null=True, verbose_name='date lutte'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='dead_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre déces'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='lutte_type',
            field=models.CharField(default='1', max_length=5, verbose_name='type de lutte'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='name_male',
            field=models.CharField(max_length=50, verbose_name='nom du père'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='remark',
            field=models.TextField(blank=True, verbose_name='remarque'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='sex',
            field=models.CharField(blank=True, max_length=50, verbose_name='sexe'),
        ),
    ]
