# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0026_auto_20180203_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutte',
            name='birth_weight_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='poids naissance 1'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='birth_weight_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='poids naissance 2'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='birth_weight_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='poids naissance 3'),
        ),
        migrations.AlterField(
            model_name='mouton',
            name='birth_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='poids à la naissance'),
        ),
    ]
