# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moutons', '0027_auto_20180203_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutte',
            name='dead_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre décès'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='male_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='moutons.Mouton', verbose_name='numéro du male'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='mouton_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='moutons.Mouton', verbose_name='N° Sanitel'),
        ),
        migrations.AlterField(
            model_name='lutte',
            name='name_male',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nom du père'),
        ),
    ]
